name: Workflow for Codecov Action
on: [push, pull_request]

jobs:
  Covergae:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov!
        uses: codecov/codecov-action@v3
