name: Workflow for Codecov Action
on: [push, pull_request]

jobs:
  Covergae:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install requirements
        run: pip install -r requirements_dev.txt
