name: Workflow for Codecov Action
on: [push, pull_request]

jobs:
  Covergae:
    runs-on: ubuntu-latest
    steps:
      - name: Upload coverage reports to Codecov!
        uses: codecov/codecov-action@v3
        run: |
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x ./tests/coverage.xml
          ./tests/codeverage.xml -t ${CODECOV_TOKEN}
        #token: ${{ secrets.CODECOV_TOKEN }}
