name: Workflow for Codecov Action
on: [push, pull_request]

jobs:
  Coverage:
    steps:
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        token: ${{ secrets.CODECOV_TOKEN }}
